## CNN Train V2
Author: Dalyah Aljamal, 27 April 2018
#This script will train the ICVL dataset to perform hand pose estimation
#Accuracy and loss will be calculated

In [3]:
#read and load data_preprocessing file
using Knet, Plots, JLD, NBInclude
setseed(123)
nbinclude("data_preprocessing.ipynb")

## Training version 2

In [4]:
#100 Samples for the training and 20 for testing , 20 is minibatch size to make sure the model is working fine 
#next assignment I will Train the model on the whole dataset
Atype = gpu() >= 0 ? KnetArray{Float32} : Array{Float32}

rootpath="imgDraft2/Training/Depth" 
arr1 = ["-112-5"]
arr2 = ["201403121135"]
trn_labelpath="imgDraft2/Training/labels.txt"
tst_labelpath="imgDraft2/Testing/tst_seq1.txt"

tst_rootpath="imgDraft2/Testing/Depth" 
tst_arr1 = ["tst_seq_1"]

trn_labels= read_labels(trn_labelpath) # (48, )
xtrn= read_img(rootpath,arr1,arr2, Atype);
ytrn= read_labels(trn_labelpath);
#ytrn= convert(Array{UInt8},ytrn)

xtst= read_tst_img(tst_rootpath,tst_arr1, Atype);
ytst= read_labels(tst_labelpath);
#ytst= convert(Array{UInt8},ytst)
n_samples=size(xtrn,4)
ind = randperm(n_samples)
#SHefelling Data
xtrn=xtrn[:,:,:,ind[1:n_samples]]
ytrn=ytrn[:,ind[1:n_samples]]


BS=20;
dtrn = dataset_minibatching(BS, xtrn, ytrn, Atype);
dtst= dataset_minibatching(BS, xtst, ytst, Atype);

summary(xtrn)

trn image :-112-5/201403121135/image_0000-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0001-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0002-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0003-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0004-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0005-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0006-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0007-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0008-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0009-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0010-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn image :-112-5/201403121135/image_0011-Copy1.png
2
128×128×1×1 Array{Float32,4}
trn 

tst image :tst_seq_1/image_0000-Copy1.png
calculating segm label
Passed indmax
4
5
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0001-Copy1.png
calculating segm label
Passed indmax
4
5
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0002-Copy1.png
calculating segm label
Passed indmax
4
5
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0003-Copy1.png
calculating segm label
Passed indmax
4
5
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0004-Copy1.png
calculating segm label
Passed indmax
4
5
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0005-Copy1.png
calculating segm label
Passed indmax
4
5
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0006-Copy1.png
calculating segm label
Passed indmax
5
6
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0007-Copy1.png
calculating segm label
Passed indmax
1
2
128×128×1×1 Array{Float32,4}
tst image :tst_seq_1/image_0008-Copy1.png
calculating segm label
Passed indmax
5
6
128×128×1×1 Array{Flo

"128×128×1×100 Array{Float32,4}"

In [5]:
(x,y)= first(dtrn)
map(summary, (x,y))


("128×128×1×20 Knet.KnetArray{Float32,4}", "48×20 Knet.KnetArray{Float32,2}")

In [6]:
#Checking Diemtionalities

#Desired Dim for (xtrn, ytrn, xtst, ytst)
#("128×128×1×60000 Array{Float32,4}", "60000-element Array{UInt8,1}",
#"128×128×1×10000 Array{Float32,4}", "10000-element Array{UInt8,1}")

println(map(summary,(xtrn,ytrn,xtst,ytst)))
println("Num of MiniBatches")
println(length(dtrn))# Return number of MiniBatches size
println("ytrn")

(x,y)= first(dtrn);
println(map(summary,(x,y)));
#for (x, y) in dtrn
 #   
#end

("128×128×1×100 Array{Float32,4}", "48×100 Array{Float32,2}", "128×128×1×20 Array{Float32,4}", "48×20 Array{Float32,2}")
Num of MiniBatches
5
ytrn
("128×128×1×20 Knet.KnetArray{Float32,4}", "48×20 Knet.KnetArray{Float32,2}")


In [7]:
xtrn[:,:,:,30]

128×128×1 Array{Float32,3}:
[:, :, 1] =
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [8]:
ytrn

48×100 Array{Float32,2}:
 160.0   160.0   160.0   160.0   160.0   …  160.0   160.0   160.0   160.0 
 120.0   120.0   120.0   120.0   120.0      120.0   120.0   120.0   120.0 
 272.56  273.95  271.64  272.61  273.32     272.88  273.88  272.34  271.79
 159.38  157.6   159.62  160.32  158.83     158.19  158.47  160.05  159.66
  93.5    92.97   92.87   93.5    93.13      92.99   92.63   93.53   93.17
 255.8   266.91  255.39  256.41  268.81  …  267.61  261.61  256.13  255.68
 186.25  171.69  186.29  187.84  169.75     169.88  180.65  187.42  186.23
  78.01   71.12   76.87   78.47   70.45      70.4    73.79   78.03   77.32
 253.12  253.71  251.88  254.11  254.49     253.51  253.07  253.53  251.75
 208.84  186.83  208.79  210.33  182.53     183.34  200.61  209.72  208.55
  70.43   57.68   69.08   71.1    56.32  …   56.3    63.03   70.03   69.24
 243.99  231.75  240.6   244.02  230.85     230.28  236.09  242.84  239.97
 212.87  200.81  213.32  213.1   194.42     196.45  210.48  212.98  213.08


In [9]:
ytst

48×20 Array{Float32,2}:
 180.21   181.036  181.637  181.341  …  179.149  179.332  180.331  180.941
 145.428  145.507  145.143  144.16      139.903  140.313  140.163  139.735
 368.854  368.683  368.327  368.118     387.952  389.155  389.402  389.678
 164.594  165.609  165.989  165.771     172.161  171.94   172.351  173.033
 154.94   155.079  154.959  154.524     149.992  150.315  150.199  150.425
 355.87   355.55   354.972  354.16   …  364.995  365.248  365.32   365.246
 146.301  147.543  147.685  147.486     171.894  171.125  171.259  171.619
 143.254  143.217  143.445  143.678     136.825  136.87   136.893  137.557
 354.851  355.01   354.167  351.742     353.994  354.576  354.41   354.128
 133.131  134.516  134.459  134.202     183.962  182.869  182.776  182.791
 132.517  132.109  132.543  133.127  …  128.15   127.829  127.557  127.743
 349.555  351.307  350.168  345.221     350.381  350.884  350.642  350.673
 163.659  164.495  164.867  165.354     163.806  163.759  165.001  165.774
 

## CNN Model

1. Predict Function
2. Loss Function
3. Loss Gradient
4. Prameter Intialization
5. Trian Function


## Hyber Parameters

Batch size: 128

Momentum: 0.9

Weight decay: 0.001

Learning  rate: 0.01

Epoch number: 100

PCA Components: 30

## LOSS

In [10]:
#Loss Functions

#Mean Loss
#loss(w,x,y)= mean(abs2,y-predict(w,x))
function loss(w,x,y)
    return mean(abs2,y-predict(w,x))
end

#Huber Loss
function huber_loss(w, x, y ; e=0.4)
    ypred=predict(w,x)
    N= size(y,1)
    E=e# ill(e, N)
    com=abs(y - ypred) .<= E
    
    out = true
    for i in 1:length(s)
        if  s[i] != true
            out=false
        end
    end
    if out
        lo= 0.5* (y- ypred).^2
    else
        lo=e* abs(y - ypred) - 0.5 * (E .^2)
        
    end
    return lo
end

#Gradient Loss
lossgradient = grad(loss);

## CNN Model Predict 

In [11]:
#Conv 8(5*5) , Max Pool (4*4), Conv 8(5*5), Max Pool (2*2), Conv 8(3*3), 2 FC (1024),droupout, PCA (30), FC(48)
function predict(w,x; pdrop=0.3)
  
    x = pool(relu.(conv4(w[1],x) .+ w[2]); window=4) 
    
    #Second Conv Layer
    x = pool(relu.(conv4(w[3],x) .+ w[4]); window=2) 
    
    #Third Conv Layer
    x = relu.(conv4(w[5],x) .+ w[6])
    
    #FC 1
    x = relu.(w[7]*mat(x) .+ w[8])
    
    #FC 2
    x = relu.(w[9]* x .+ w[10])
    
    #Dropout layer
    x= dropout(x,pdrop);
    
    #PCA layer
    
    #OUTPUT
    return w[11]* x .+ w[12]
    
end

predict (generic function with 1 method)

## Parameter Intialization

In [12]:

#DimensionMismatch("((1024, 103968), (968, 120), (1024, 120))")

wcnn=map(Atype, [ 0.1* randn(5,5,1,8),  zeros(1,1,8,1), 
        0.1* randn(5,5,8,8),  zeros(1,1,8,1),
        0.1* randn(3,3,8,8),  zeros(1,1,8,1), #103968
        0.1* randn(1024,968),  zeros(1024,1),
        0.1* randn(1024,1024),  zeros(1024,1), # add PCA Layer parameters later
        0.1* randn(48,1024), zeros(48,1)]);

In [13]:
#TRAIN CNN Function

function train!(w, data, optims; lr=.01)
   
    wd=0.008;   #for regularization 
    for (x,y) in data
        dw = lossgradient(w, x, y)
        println("dw")
        @show (map(vecnorm, dw))
        update!(w, dw, optims)
        println("W")
         @show (map(vecnorm, w))
        #for i in 1:length(w) # Loop  over W and B
         #  #@time print(w[i] -= lr * dw[i])
         #   w[i] = w[i]- lr * dw[i]# - lr*w[i]* wd
        #end
    end
    
    return w
end

train! (generic function with 1 method)

## TRAINING

In [14]:
#MAIN
#optims = optimizers(wcnn, Momentum(;lr=0.1,gclip=10.0))
optims = map(x->Momentum(;lr=0.01,gclip=10.0, gamma=0.9),wcnn)
@time cnnmodels = [ copy(train!(wcnn, dtrn, optims)) for epoch=1:100 ];


dw
map(vecnorm, dw) = Float32[2126.49, 529.948, 3222.93, 572.915, 3882.8, 793.169, 2891.46, 273.064, 3190.96, 131.451, 3305.83, 58.4956]
W
map(vecnorm, w) = Float32[1.50864, 0.1, 3.96641, 0.1, 2.3787, 0.1, 99.4998, 0.1, 102.356, 0.1, 22.2135, 0.1]
dw
map(vecnorm, dw) = Float32[1481.55, 437.248, 1961.5, 339.834, 2022.81, 517.502, 862.062, 236.581, 989.399, 118.684, 1099.57, 57.4936]
W
map(vecnorm, w) = Float32[1.51803, 0.14423, 3.97031, 0.156656, 2.38599, 0.193139, 99.5002, 0.269604, 102.356, 0.280132, 22.2152, 0.289978]
dw
map(vecnorm, dw) = Float32[4361.89, 1114.45, 4715.0, 1085.54, 5475.27, 1423.6, 2857.81, 273.116, 3080.64, 125.798, 3204.06, 57.0425]
W
map(vecnorm, w) = Float32[1.56291, 0.212242, 3.98722, 0.273025, 2.41402, 0.352436, 99.5015, 0.502701, 102.357, 0.533029, 22.2213, 0.56095]
dw
map(vecnorm, dw) = Float32[14392.4, 3511.95, 16699.0, 2779.39, 18107.0, 2277.32, 9653.15, 251.347, 10190.1, 110.973, 10754.9, 48.966]
W
map(vecnorm, w) = Float32[1.66052, 0.363431, 4.02451, 0.47

W
map(vecnorm, w) = Float32[2.54762, 2.64677, 5.00622, 1.96839, 3.24117, 1.75769, 99.5457, 3.36597, 102.374, 3.59602, 22.2033, 3.88086]
dw
map(vecnorm, dw) = Float32[23356.7, 6581.78, 46290.4, 3574.0, 22560.7, 5826.07, 10713.7, 305.939, 7217.45, 94.7803, 5492.35, 25.3975]
W
map(vecnorm, w) = Float32[2.5642, 2.72803, 5.0325, 2.01219, 3.25517, 1.77283, 99.5462, 3.38932, 102.374, 3.61976, 22.1963, 3.92013]
dw
map(vecnorm, dw) = Float32[20755.2, 5456.44, 44147.6, 3548.56, 22251.4, 5158.25, 9946.18, 273.077, 6871.31, 84.417, 5283.26, 22.4919]
W
map(vecnorm, w) = Float32[2.60769, 2.78185, 5.06215, 2.09034, 3.28663, 1.84827, 99.5485, 3.44417, 102.376, 3.68523, 22.206, 4.05289]
dw
map(vecnorm, dw) = Float32[17138.9, 4944.96, 44934.3, 2925.62, 27085.1, 2987.69, 10396.0, 155.159, 7155.4, 45.9678, 5340.39, 11.0553]
W
map(vecnorm, w) = Float32[2.61279, 2.85455, 5.08424, 2.12332, 3.29863, 1.85391, 99.5487, 3.46178, 102.375, 3.70352, 22.1985, 4.0832]
dw
map(vecnorm, dw) = Float32[15373.9, 4270.79, 3

map(vecnorm, dw) = Float32[1.31962f5, 31012.6, 80775.6, 13808.1, 67027.6, 10872.9, 33764.1, 491.087, 26120.2, 146.042, 20028.2, 34.9846]
W
map(vecnorm, w) = Float32[2.4456, 3.94798, 5.45343, 3.10073, 3.59814, 2.01211, 99.5655, 3.81956, 102.366, 3.96117, 21.8623, 3.48593]
dw
map(vecnorm, dw) = Float32[1.28811f5, 30841.7, 95645.5, 15112.7, 79185.3, 12598.2, 38759.6, 567.402, 30834.0, 169.432, 23552.8, 39.799]
W
map(vecnorm, w) = Float32[2.42955, 3.97942, 5.44997, 3.07664, 3.58091, 1.95704, 99.5641, 3.80697, 102.364, 3.94033, 21.8385, 3.41747]
dw
map(vecnorm, dw) = Float32[15593.5, 3996.73, 15870.2, 2488.31, 15066.1, 3191.51, 7899.97, 156.531, 6341.58, 48.1409, 4849.43, 11.2675]
W
map(vecnorm, w) = Float32[2.37356, 4.05236, 5.43768, 3.01063, 3.54066, 1.86394, 99.5605, 3.77026, 102.359, 3.88945, 21.7996, 3.26786]
dw
map(vecnorm, dw) = Float32[14029.8, 3823.51, 13634.1, 3078.11, 14584.5, 4495.78, 7542.02, 238.824, 6267.3, 77.5148, 4865.77, 20.6036]
W
map(vecnorm, w) = Float32[2.38566, 4.066

W
map(vecnorm, w) = Float32[2.63518, 5.19024, 6.19872, 3.67035, 3.97083, 1.79638, 99.5748, 4.12824, 102.354, 4.28078, 21.6501, 4.73112]
dw
map(vecnorm, dw) = Float32[1659.26, 420.887, 3398.13, 7798.09, 14586.5, 3659.6, 7484.69, 294.676, 5833.01, 90.4354, 3847.8, 18.9884]
W
map(vecnorm, w) = Float32[2.64992, 5.21486, 6.22019, 3.70582, 3.98985, 1.81683, 99.5773, 4.15515, 102.357, 4.32385, 21.6727, 4.91509]
dw
map(vecnorm, dw) = Float32[1161.54, 305.846, 2473.71, 4640.53, 8730.67, 2140.88, 4476.0, 163.596, 3507.88, 49.4963, 2411.6, 10.494]
W
map(vecnorm, w) = Float32[2.71746, 5.18303, 6.24689, 3.79096, 4.0368, 1.87841, 99.5822, 4.20625, 102.362, 4.40574, 21.7159, 5.18016]
dw
map(vecnorm, dw) = Float32[3941.39, 959.376, 7817.51, 11175.1, 20805.5, 4573.4, 11846.7, 315.982, 9002.13, 87.4963, 5924.18, 16.1257]
W
map(vecnorm, w) = Float32[2.7318, 5.21232, 6.26842, 3.81607, 4.05139, 1.89424, 99.5843, 4.22937, 102.364, 4.44109, 21.7332, 5.32557]
dw
map(vecnorm, dw) = Float32[6101.33, 1638.76, 11

map(vecnorm, dw) = Float32[6044.88, 1667.14, 9165.52, 12197.1, 21195.6, 3621.11, 14502.4, 316.383, 10368.6, 95.1661, 6611.8, 17.8553]
W
map(vecnorm, w) = Float32[2.91898, 6.67824, 6.56196, 3.83119, 4.16057, 1.82423, 99.5868, 4.31956, 102.354, 4.38811, 21.538, 4.97761]
dw
map(vecnorm, dw) = Float32[1730.16, 469.799, 2377.08, 3859.94, 6774.38, 1216.07, 4530.0, 111.44, 3294.1, 34.2541, 2133.69, 6.61116]
W
map(vecnorm, w) = Float32[2.89555, 6.69501, 6.55881, 3.75238, 4.11485, 1.76665, 99.5838, 4.2891, 102.35, 4.3393, 21.5027, 4.91437]
dw
map(vecnorm, dw) = Float32[1365.75, 311.858, 1740.1, 6390.06, 10806.9, 2109.68, 6587.88, 206.524, 4701.33, 68.259, 3039.69, 14.023]
W
map(vecnorm, w) = Float32[2.92138, 6.69381, 6.56785, 3.73262, 4.1052, 1.75233, 99.5833, 4.28689, 102.349, 4.33108, 21.4932, 4.95471]
dw
map(vecnorm, dw) = Float32[2006.4, 443.607, 2375.75, 7435.32, 13015.4, 2554.24, 7551.64, 259.381, 5442.31, 86.3598, 3477.1, 17.6767]
W
map(vecnorm, w) = Float32[3.00226, 6.65069, 6.58789, 3.

W
map(vecnorm, w) = Float32[3.02999, 7.27963, 6.8669, 4.068, 4.28574, 2.07658, 99.6, 4.68373, 102.354, 4.66522, 21.4023, 5.2899]
dw
map(vecnorm, dw) = Float32[1050.72, 294.45, 157.966, 1361.24, 2927.22, 411.129, 2353.69, 27.9661, 1473.82, 9.94874, 875.218, 1.82596]
W
map(vecnorm, w) = Float32[3.06708, 7.29329, 6.91485, 4.00879, 4.2594, 2.01508, 99.5988, 4.66338, 102.351, 4.63475, 21.3763, 5.28894]
dw
map(vecnorm, dw) = Float32[350.799, 65.7969, 701.301, 3962.2, 7373.63, 2024.62, 5246.6, 165.982, 3644.33, 53.2998, 2387.73, 10.7363]
W
map(vecnorm, w) = Float32[3.11794, 7.29879, 6.96589, 4.01166, 4.26555, 2.01725, 99.6, 4.67949, 102.352, 4.65032, 21.3759, 5.38218]
dw
map(vecnorm, dw) = Float32[403.067, 47.0285, 576.03, 3619.44, 6870.75, 1883.05, 4931.87, 151.214, 3394.07, 48.1562, 2216.53, 9.50074]
W
map(vecnorm, w) = Float32[3.19354, 7.27231, 7.0255, 4.07064, 4.30037, 2.07705, 99.6033, 4.72886, 102.356, 4.70733, 21.3988, 5.55625]
dw
map(vecnorm, dw) = Float32[551.636, 103.159, 998.162, 2

W
map(vecnorm, w) = Float32[4.05674, 8.33498, 8.02368, 4.01786, 4.3243, 2.03636, 99.6148, 4.94304, 102.36, 4.9024, 21.214, 4.74568]
dw
map(vecnorm, dw) = Float32[978.431, 161.325, 1698.01, 5458.73, 12450.3, 2983.94, 7271.24, 180.742, 5206.77, 56.3822, 3462.62, 10.325]
W
map(vecnorm, w) = Float32[4.07249, 8.41202, 8.02808, 4.01438, 4.32764, 2.0319, 99.6148, 4.94116, 102.359, 4.89924, 21.2041, 4.61572]
dw
map(vecnorm, dw) = Float32[969.329, 79.5004, 1562.84, 4499.15, 10005.6, 2753.12, 6058.46, 174.379, 4485.93, 53.3624, 2967.36, 9.48402]
W
map(vecnorm, w) = Float32[4.04794, 8.4897, 8.0206, 3.95534, 4.30463, 1.96951, 99.6123, 4.90331, 102.356, 4.85345, 21.1707, 4.41306]
dw
map(vecnorm, dw) = Float32[199.651, 22.3414, 356.472, 1963.55, 4202.07, 1204.38, 2600.27, 81.5059, 1869.84, 25.7928, 1267.54, 5.21809]
W
map(vecnorm, w) = Float32[4.04849, 8.61102, 8.02382, 3.95814, 4.31023, 1.97169, 99.6125, 4.90288, 102.356, 4.85598, 21.1636, 4.27842]
dw
map(vecnorm, dw) = Float32[234.331, 38.627, 463

dw
map(vecnorm, dw) = Float32[150.133, 8.40815, 339.219, 1918.09, 3309.6, 1251.69, 2436.0, 84.9945, 1717.26, 26.1812, 1214.98, 5.09998]
W
map(vecnorm, w) = Float32[4.24106, 9.95953, 8.04409, 3.99683, 4.35346, 2.03614, 99.63, 5.07734, 102.366, 5.00751, 20.9976, 2.98483]
dw
map(vecnorm, dw) = Float32[290.805, 45.5655, 540.99, 3338.59, 6083.85, 1972.39, 4255.91, 124.587, 2912.51, 37.0009, 2040.14, 6.71441]
W
map(vecnorm, w) = Float32[4.265, 9.97509, 8.04497, 3.99364, 4.3539, 2.03267, 99.6302, 5.08228, 102.366, 5.00723, 20.9921, 2.992]
dw
map(vecnorm, dw) = Float32[363.019, 60.9499, 503.123, 2990.89, 5619.41, 1758.8, 3962.79, 109.351, 2680.65, 33.0817, 1913.47, 6.07239]
W
map(vecnorm, w) = Float32[4.23957, 10.0344, 8.03458, 3.93475, 4.32569, 1.97222, 99.6281, 5.04954, 102.362, 4.96292, 20.9634, 2.95062]
dw
map(vecnorm, dw) = Float32[206.484, 28.865, 405.343, 2532.79, 4761.85, 1644.54, 3195.12, 108.751, 2181.82, 33.7019, 1555.69, 6.61059]
W
map(vecnorm, w) = Float32[4.26329, 10.0427, 8.0341

map(vecnorm, dw) = Float32[9198.27, 1861.53, 348.049, 2878.99, 4875.37, 1769.87, 4061.94, 133.304, 2538.29, 40.6452, 1766.6, 7.70591]
W
map(vecnorm, w) = Float32[5.13471, 10.3781, 8.22187, 3.93487, 4.37009, 1.9699, 99.6383, 5.17068, 102.366, 5.09923, 20.8588, 2.9854]
dw
map(vecnorm, dw) = Float32[520.4, 129.064, 478.788, 2696.67, 6422.41, 1445.21, 5069.59, 108.597, 2706.87, 34.524, 1695.83, 6.88288]
W
map(vecnorm, w) = Float32[5.19485, 10.3252, 8.24615, 3.99161, 4.3911, 2.03249, 99.6401, 5.22091, 102.37, 5.15486, 20.8798, 3.05933]
dw
map(vecnorm, dw) = Float32[3957.22, 845.224, 2597.43, 3141.46, 6277.25, 1726.12, 4605.59, 112.095, 2749.87, 32.9799, 1868.34, 5.83409]
W
map(vecnorm, w) = Float32[5.27188, 10.2294, 8.26848, 3.98889, 4.38576, 2.02989, 99.6398, 5.22367, 102.369, 5.15838, 20.8746, 3.07909]
dw
map(vecnorm, dw) = Float32[77.7117, 3.87315, 1194.37, 2626.51, 4930.52, 1402.41, 2991.46, 91.4331, 2059.38, 27.6174, 1499.42, 4.90678]
W
map(vecnorm, w) = Float32[5.31889, 10.164, 8.2891

map(vecnorm, w) = Float32[5.69375, 11.0821, 8.90425, 3.96755, 4.39324, 1.98688, 99.6418, 5.4153, 102.365, 5.2411, 20.7135, 2.87092]
dw
map(vecnorm, dw) = Float32[62.2086, 18.177, 722.751, 1429.02, 3723.15, 684.245, 2390.13, 48.4041, 1319.4, 16.668, 918.263, 3.72835]
W
map(vecnorm, w) = Float32[5.75138, 11.1211, 8.9234, 4.02261, 4.41582, 2.05249, 99.6433, 5.47654, 102.367, 5.29275, 20.7253, 2.82331]
dw
map(vecnorm, dw) = Float32[551.511, 232.833, 4080.44, 7135.39, 16882.3, 3062.45, 11189.0, 205.092, 6181.93, 61.4027, 3977.95, 11.4277]
W
map(vecnorm, w) = Float32[5.86581, 11.0969, 8.94403, 4.01962, 4.41722, 2.0567, 99.643, 5.48755, 102.366, 5.29205, 20.7129, 2.70657]
dw
map(vecnorm, dw) = Float32[270.722, 113.485, 2282.03, 3646.38, 8729.33, 1598.97, 5790.98, 110.443, 3219.73, 32.8467, 2076.14, 6.20404]
W
map(vecnorm, w) = Float32[6.03777, 11.0167, 8.9681, 3.96472, 4.40031, 2.00658, 99.6413, 5.45332, 102.363, 5.24551, 20.6799, 2.56354]
dw
map(vecnorm, dw) = Float32[513.13, 224.939, 2828.9

map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 9228.98, 10021.4, 2182.77, 11945.2, 156.326, 6342.12, 59.9634, 4551.26, 15.3909]
W
map(vecnorm, w) = Float32[4.28576, 17.2906, 10.2298, 3.70163, 4.61608, 2.14405, 99.6488, 5.49196, 102.341, 5.06981, 20.3145, 1.91681]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 10789.3, 11669.2, 2614.1, 13864.9, 192.511, 7298.6, 75.0536, 5155.56, 19.6599]
W
map(vecnorm, w) = Float32[4.27999, 17.333, 10.2438, 3.7269, 4.63606, 2.16184, 99.6498, 5.51939, 102.342, 5.09241, 20.3224, 1.8876]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 6733.45, 7270.47, 1564.09, 8574.13, 108.703, 4615.21, 41.482, 3340.35, 10.8054]
W
map(vecnorm, w) = Float32[4.27512, 17.3713, 10.2564, 3.7941, 4.68775, 2.20599, 99.6521, 5.58897, 102.346, 5.15241, 20.3475, 1.86006]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 9785.42, 10442.1, 2042.02, 12225.2, 126.033, 6795.58, 44.9528, 4938.23, 10.926]
W
map(vecnorm, w) = Float32[4.27099, 17.4058, 10.2679, 3.81225, 4.70264, 2.22227, 99.6529, 5.60904,

dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 6064.49, 6651.8, 1464.69, 7305.31, 95.5395, 3992.5, 36.1551, 2819.2, 9.44992]
W
map(vecnorm, w) = Float32[4.24547, 17.7075, 10.3708, 3.69679, 4.61869, 2.23863, 99.6509, 5.56369, 102.337, 5.15238, 20.2388, 2.04127]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 7816.53, 8594.54, 1945.28, 9440.37, 131.004, 5026.05, 49.5901, 3536.52, 12.4929]
W
map(vecnorm, w) = Float32[4.24541, 17.7084, 10.3711, 3.72235, 4.6368, 2.25978, 99.6518, 5.5912, 102.338, 5.17445, 20.2483, 2.03522]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 3710.64, 4085.98, 886.872, 4463.84, 56.6694, 2459.39, 21.2812, 1788.56, 5.64997]
W
map(vecnorm, w) = Float32[4.24537, 17.7093, 10.3714, 3.78969, 4.68595, 2.31399, 99.6541, 5.65886, 102.343, 5.23135, 20.2755, 2.01835]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 18224.2, 19789.4, 3897.63, 21599.3, 223.571, 12238.8, 78.2691, 8702.64, 18.5559]
W
map(vecnorm, w) = Float32[4.24533, 17.7101, 10.3717, 3.8082, 4.69923, 2.33237, 99.6548, 5.6

dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 16505.3, 18801.7, 3752.34, 19479.4, 209.797, 11094.0, 72.0117, 8368.45, 17.461]
W
map(vecnorm, w) = Float32[4.24498, 17.7169, 10.3741, 3.71325, 4.61326, 2.36647, 99.6521, 5.62833, 102.337, 5.20633, 20.1337, 4.47113]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 4068.88, 4707.26, 1036.74, 4882.45, 64.6667, 2681.28, 23.4965, 2144.84, 6.43702]
W
map(vecnorm, w) = Float32[4.24498, 17.7169, 10.3741, 3.6967, 4.60133, 2.35471, 99.6515, 5.61306, 102.335, 5.19463, 20.1218, 4.63156]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 8685.68, 10179.6, 2304.52, 10461.5, 146.914, 5686.89, 54.174, 4315.25, 14.7179]
W
map(vecnorm, w) = Float32[4.24497, 17.7169, 10.3741, 3.72226, 4.61846, 2.38123, 99.6524, 5.64032, 102.337, 5.21869, 20.1288, 4.68622]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 3950.89, 4610.68, 1000.94, 4742.3, 60.9787, 2626.48, 21.9936, 2119.55, 6.22686]
W
map(vecnorm, w) = Float32[4.24497, 17.7169, 10.3741, 3.78961, 4.66516, 2.44874, 99.6549, 5

dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 29386.0, 35025.4, 6735.93, 34219.9, 346.581, 19725.9, 110.78, 16825.5, 29.0421]
W
map(vecnorm, w) = Float32[4.24496, 17.7171, 10.3742, 3.77985, 4.64135, 2.53408, 99.6556, 5.7636, 102.34, 5.35524, 20.0308, 8.61532]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 13977.7, 16763.7, 3345.6, 16300.4, 178.276, 9301.55, 58.3065, 7873.05, 15.4803]
W
map(vecnorm, w) = Float32[4.24496, 17.7171, 10.3742, 3.71325, 4.59646, 2.46322, 99.6531, 5.701, 102.335, 5.29972, 20.0016, 8.85531]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 4734.01, 5837.11, 1285.58, 5624.3, 75.5517, 3108.9, 26.1425, 2686.78, 7.62717]
W
map(vecnorm, w) = Float32[4.24496, 17.7171, 10.3742, 3.69671, 4.58514, 2.4479, 99.6525, 5.68771, 102.334, 5.28707, 19.9924, 8.99733]
dw
map(vecnorm, dw) = Float32[0.0, 0.0, 0.0, 8251.81, 10219.7, 2313.57, 9814.17, 139.741, 5346.78, 48.7655, 4541.82, 14.3032]
W
map(vecnorm, w) = Float32[4.24496, 17.7171, 10.3742, 3.72227, 4.60144, 2.47799, 99.6535, 5.7172

In [15]:
trncnnloss=0
tstcnnloss =0
c=1
trncnnlosses= []
tstcnnlosses= []
@time for w in cnnmodels
    trncnnloss =mean( [loss(w,x,y) for (x,y) in dtrn ]); 
    push!(trncnnlosses, trncnnloss)
   
end
@time for w in cnnmodels
    tstcnnloss =mean( [loss(w,x,y) for (x,y) in dtst ]); 
   push!(tstcnnlosses, tstcnnloss)
end

println(trncnnlosses)
println(tstcnnlosses)

  1.671714 seconds (346.21 k allocations: 15.669 MiB, 9.45% gc time)
  0.419145 seconds (79.61 k allocations: 2.953 MiB, 37.79% gc time)
Any[3273.83, 3214.06, 3580.78, 3432.14, 3375.15, 3164.33, 3144.26, 3383.76, 3232.78, 3659.11, 3192.86, 3252.55, 3306.37, 3409.28, 3161.25, 2929.23, 2992.5, 3353.27, 3536.84, 3181.16, 3021.13, 3476.65, 3454.87, 3244.05, 3508.36, 3103.8, 3118.41, 3485.85, 3363.14, 3247.73, 3083.9, 3163.23, 3221.33, 3132.56, 2987.5, 3205.27, 3421.35, 3114.32, 3233.0, 3220.69, 3189.4, 2938.27, 3264.73, 3294.28, 3119.12, 3179.91, 3195.54, 3106.29, 3368.39, 3452.63, 3222.97, 3526.32, 2930.27, 3189.35, 3305.52, 3072.79, 3082.88, 3285.31, 3340.11, 3179.89, 3324.93, 3002.48, 3307.69, 3410.1, 3304.4, 3152.09, 3164.25, 3157.25, 3353.44, 3408.23, 3051.24, 3270.13, 3256.73, 3148.25, 3373.24, 3177.45, 3239.85, 3433.56, 3336.97, 2925.87, 3206.7, 3147.45, 3232.06, 3284.1, 3305.29, 3202.76, 3730.82, 3130.12, 3167.84, 3258.78, 3187.46, 3052.96, 3135.65, 3342.03, 3104.06, 3480.82, 3165.

In [18]:
#Plotting Training Loss


plot( [trncnnlosses],ylim=(.000,.010),labels=[ :trncnnlosses ],xlabel="Epochs",ylabel="Loss") 

In [17]:
plot( [tstcnnlosses],ylim=(.000,.010),labels=[ :tstcnnlosses ],xlabel="Epochs",ylabel="Loss") 